/**
 * Async Subagent Extension — Non-blocking subagent execution via RPC mode.
 *
 * Subagents run in background pi processes using RPC mode. The parent
 * remains interactive and can check progress, steer, or stop subagents
 * at any time. Results are delivered as injected user messages.
 */

import { spawn, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";
import * as fs from "node:fs";
import * as net from "node:net";
import * as os from "node:os";
import * as path from "node:path";
import type { AgentToolResult } from "@earendil-works/pi-agent-core";
import type { ExtensionAPI, ToolDefinition } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { type AgentConfig, type AgentScope, discoverAgents } from "./agents.ts";
import { truncateToWidth } from "@earendil-works/pi-tui";

// ── Constants ───────────────────────────────────────────────────────────────

const MAX_TURNS_HARD = 500;
const STOP_TIMEOUT_MS = 5 * 60 * 1000; // 5 minutes
const HARD_KILL_DELAY_MS = 5000;
const STARTUP_SUMMARY_EVENT = "pi-config:startup-summary-item";
const REVIEW_ROUND_CAP = 3;

// ── Reviewer-spawn tracker ────────────────────────────────────────────────
//
// Tracks which post-implementation reviewer kinds each parent (the running pi
// process) has spawned. The orchestrator's `subagent_review_status` tool reads
// the persisted form of this map to mechanically verify that an implementer's
// declared `reviewParentRequirements` are met before forwarding `complete`.
//
// Two views of the same data:
//   - `parentReviewerSpawns`: in-memory `Map<parentSessionId, SpawnEntry[]>`,
//     used by the soft-prompt check at parent-stop time. Per-process; lost on
//     restart (documented; not a bug).
//   - `/tmp/pi-subagent-<parentSessionId>.reviewers.json`: durable file the
//     orchestrator reads via `subagent_review_status`. Persisted on every
//     spawn so cross-process visibility survives the harness restarting.
//
// When the parent is itself a subagent (e.g. implement-flash running in RPC
// mode), `ctx.sessionManager.getSessionId()` returns the parent's session id;
// if unavailable, fall back to `pid:<process.pid>`. The fallback only matters
// in nested-orchestration scenarios; normal pi sessions always have a
// session id.

import type { ReviewerKind } from "./agents.ts";

interface SpawnEntry {
	reviewerKind: ReviewerKind;
	childSessionId: string;
	childAgentName: string;
	spawnedAt: number;
}

interface TrackerState {
	spawns: SpawnEntry[];
	reviewRounds: number;
	reviewCapReached: boolean;
}

const parentReviewerSpawns = new Map<string, TrackerState>();

/** Stable key for tracker persistence and cross-process lookup. */
function getParentTrackerKey(ctx: any): string {
	try {
		const id = ctx?.sessionManager?.getSessionId?.();
		if (typeof id === "string" && id.length > 0) return id;
	} catch { /* sessionManager not present — fall through */ }
	return `pid:${process.pid}`;
}

/** On-disk path for a parent's reviewer-spawn log (read by orchestrator tool). */
function reviewStatusPath(parentKey: string): string {
	// Sanitize: strip characters that would break a path. The session id is
	// generated by the parent process and is normally safe, but a malicious or
	// buggy upstream could produce anything. Keep this conservative.
	const safe = parentKey.replace(/[^A-Za-z0-9._-]+/g, "_").slice(0, 200) || `pid_${process.pid}`;
	return `/tmp/pi-subagent-${safe}.reviewers.json`;
}

function recordReviewerSpawn(parentKey: string, entry: SpawnEntry): void {
	const state = parentReviewerSpawns.get(parentKey) ?? { spawns: [], reviewRounds: 0, reviewCapReached: false };
	state.spawns.push(entry);
	state.reviewRounds++;
	if (state.reviewRounds >= REVIEW_ROUND_CAP) {
		state.reviewCapReached = true;
	}
	parentReviewerSpawns.set(parentKey, state);

	// Persist atomically: write to a temp file then rename. Avoids partial
	// reads if the orchestrator polls while we write.
	try {
		const target = reviewStatusPath(parentKey);
		const tmp = `${target}.tmp.${process.pid}`;
		fs.writeFileSync(tmp, JSON.stringify({
			parentSessionId: parentKey,
			updatedAt: Date.now(),
			spawns: state.spawns,
			reviewRounds: state.reviewRounds,
			reviewCapReached: state.reviewCapReached,
		}, null, 2));
		fs.renameSync(tmp, target);
	} catch (e) {
		debugLog(`recordReviewerSpawn: persist failed: ${e instanceof Error ? e.message : String(e)}`);
	}
}

/**
 * Read the persisted spawn list for a given session id. Used by:
 *   1. The soft-prompt check at child-stop time (parent's harness reads the
 *      child's tracker file).
 *   2. The `subagent_review_status` tool (orchestrator's harness reads the
 *      implementer's tracker file).
 * Returns an empty TrackerState on any error (missing file, parse failure, IO error).
 * Never throws — this is a best-effort signal; gate enforcement belongs to the
 * orchestrator, not the harness.
 */
function readPersistedSpawns(parentSessionId: string): TrackerState {
	try {
		const path = reviewStatusPath(parentSessionId);
		const raw = fs.readFileSync(path, "utf-8");
		const parsed = JSON.parse(raw);
		const spawns = Array.isArray(parsed.spawns) ? parsed.spawns as SpawnEntry[] : [];
		const reviewRounds = typeof parsed.reviewRounds === "number" ? parsed.reviewRounds : spawns.length > 0 ? 1 : 0;
		const reviewCapReached = parsed.reviewCapReached === true;
		return { spawns, reviewRounds, reviewCapReached };
	} catch { /* missing or malformed — treat as empty */ }
	return { spawns: [], reviewRounds: 0, reviewCapReached: false };
}

/** Drop the in-memory entry when a parent ends (avoid growth across sessions). */
function clearParentTracker(parentKey: string): void {
	parentReviewerSpawns.delete(parentKey);
	// Note: we intentionally do NOT delete the on-disk file here — the
	// orchestrator may still want to read it after this parent has stopped.
	// A subsequent spawn from a new parent with the same key (unlikely but
	// possible with the pid fallback) will overwrite the file.
}

/**
 * Module-level debug logger. No-op unless PI_ASYNC_DEBUG=1 is set. Used by
 * tracker helpers and the spawn code (the spawn code previously had its own
 * closure-scoped debugLog; we keep one canonical helper at module scope so
 * tracker logic can log too).
 */
function debugLog(msg: string): void {
	if (!process.env.PI_ASYNC_DEBUG) return;
	try { fs.appendFileSync("/tmp/pi-async-debug.log", `[${process.pid}] ${msg}\n`); } catch { /* */ }
}

// ── Meta-file helpers ──────────────────────────────────────────────────────
// Atomic read/write for /tmp/pi-subagent-<sid>.meta.json, matching the
// recordReviewerSpawn pattern (tmp + rename) to avoid torn reads.

export function metaPath(sessionId: string): string {
	return `/tmp/pi-subagent-${sessionId}.meta.json`;
}

/** Write a complete meta file atomically. */
export function writeMetaJson(sessionId: string, data: Record<string, any>): void {
	try {
		const target = metaPath(sessionId);
		const tmp = `${target}.tmp.${process.pid}`;
		fs.writeFileSync(tmp, JSON.stringify(data, null, 2));
		fs.renameSync(tmp, target);
	} catch (e) {
		debugLog(`writeMetaJson: failed: ${e instanceof Error ? e.message : String(e)}`);
	}
}

/** Read a meta file, returning null on any error (missing, malformed, etc.). */
export function readMetaJson(sessionId: string): Record<string, any> | null {
	try {
		const raw = fs.readFileSync(metaPath(sessionId), "utf-8");
		return JSON.parse(raw);
	} catch {
		return null;
	}
}

/** Update an existing meta file by merging fields (read-modify-write, atomic). */
export function updateMetaJson(sessionId: string, updates: Record<string, any>): void {
	try {
		const existing = readMetaJson(sessionId) ?? {};
		const merged = { ...existing, ...updates };
		writeMetaJson(sessionId, merged);
	} catch (e) {
		debugLog(`updateMetaJson: failed: ${e instanceof Error ? e.message : String(e)}`);
	}
}

/**
 * Resolve a subagent session ID from a full or partial (last 8+ chars)
 * identifier. Scans /tmp/pi-subagent-*.meta.json and matches on the
 * session id portion (the part between "pi-subagent-" and ".meta.json").
 * Returns the full session ID and meta if exactly one match; null if none;
 * throws with an ambiguity list if multiple match.
 */
export function resolveSubagentMeta(sessionId: string): { sid: string; meta: Record<string, any> } | null {
	let files: string[];
	try {
		files = fs.readdirSync("/tmp").filter(
			(f) => f.startsWith("pi-subagent-") && f.endsWith(".meta.json"),
		);
	} catch {
		return null;
	}

	// Extract the session id portion from the filename
	const candidates: Array<{ sid: string; meta: Record<string, any> }> = [];
	for (const f of files) {
		const sid = f.replace("pi-subagent-", "").replace(".meta.json", "");
		if (sid === sessionId || sid.endsWith(sessionId)) {
			const meta = readMetaJson(sid);
			if (meta) candidates.push({ sid, meta });
		}
	}

	if (candidates.length === 0) return null;
	if (candidates.length === 1) return candidates[0];

	// Ambiguous partial match — list candidates
	const ids = candidates.map((c) => c.sid).join(", ");
	throw new Error(
		`Ambiguous partial session id "${sessionId}" matches multiple sessions: ${ids}. ` +
			`Use a longer suffix or the full id.`,
	);
}

// ── Progress tracking ───────────────────────────────────────────────────────

interface SubagentProgress {
	turns: number;
	filesRead: Set<string>;
	filesModified: Set<string>;
	lastActions: string[]; // last 5 tool calls, newest last
	errors: string[];
	currentActivity: string;
}

interface RunningSubagent {
	proc: ChildProcess;
	sessionId: string;
	agentName: string;
	task: string;
	cwd: string;
	startedAt: number;
	progress: SubagentProgress;
	messages: any[]; // accumulated messages for final output
	stdin: NodeJS.WritableStream | null;
	resolveOnStop: ((finalMessage?: string) => void) | null; // set by stop tool
	isDone: boolean;
	logPath: string;   // live human-readable event log
	logLines: string[];     // in-memory buffer for live TUI widget
	watchHandle: any;       // setWidget handle for live updates
	sockPath: string;       // Unix socket path for external viewers
	sockServer: net.Server; // socket server
	sockClients: Set<net.Socket>; // connected viewers
	// Reviewer invocation guard: the parent agent's declared requirements.
	// Empty / undefined means "no gate applies" (the soft-prompt check is a no-op).
	reviewParentRequirements?: ReviewerKind[];
	// Worktree isolation
	worktreePath: string | null;
	isolationBranch: string | null;
	parentHeadCommit: string | null;
	parentCwd: string;
	// Cached parent tracker key (session id or `pid:<pid>` fallback) for the
	// soft-prompt guard and the cross-process persisted status file. Computed
	// at spawn time when ctx is available; reused at stop time when ctx is
	// out of scope inside the message_end handler.
	parentTrackerKey: string;
	// Captured from the child's RPC get_state response; set once after spawn.
	// Used by subagent_resume to locate the session file for later continuation.
	sessionFile?: string;
	piSessionId?: string;
}

const running = new Map<string, RunningSubagent>();
// Active wait: resolves when timer fires OR subagent completes
let activeWait: { timer: NodeJS.Timeout } | null = null;

function newProgress(): SubagentProgress {
	return {
		turns: 0,
		filesRead: new Set(),
		filesModified: new Set(),
		lastActions: [],
		errors: [],
		currentActivity: "starting...",
	};
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/** Run a git command and collect output. */
function git(args: string[], cwd: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
	return new Promise((resolve) => {
		const proc = spawn("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
		let stdout = "";
		let stderr = "";
		proc.stdout.on("data", (d: Buffer) => { stdout += d.toString(); });
		proc.stderr.on("data", (d: Buffer) => { stderr += d.toString(); });
		proc.on("close", (code) => resolve({ stdout, stderr, exitCode: code ?? 1 }));
		proc.on("error", () => resolve({ stdout, stderr, exitCode: 1 }));
	});
}

function getPiInvocation(args: string[]): { command: string; args: string[] } {
	const currentScript = process.argv[1];
	const isBunVirtualScript = currentScript?.startsWith("/$bunfs/root/");
	if (currentScript && !isBunVirtualScript && fs.existsSync(currentScript)) {
		return { command: process.execPath, args: [currentScript, ...args] };
	}
	const execName = path.basename(process.execPath).toLowerCase();
	const isGenericRuntime = /^(node|bun)(\.exe)?$/.test(execName);
	if (!isGenericRuntime) return { command: process.execPath, args };
	return { command: "pi", args };
}

// ── Worktree isolation ────────────────────────────────────────────────────

/** Create an isolated git worktree on a branch off the parent HEAD (or optional baseRef).
 *  Returns null if the cwd is not a git repo or worktree creation fails. */
async function createWorktree(
	parentCwd: string,
	sessionId: string,
	baseRef?: string,
): Promise<{ worktreePath: string; branchName: string; parentHeadCommit: string } | null> {
	try {
		const topLevel = await git(["rev-parse", "--show-toplevel"], parentCwd);
		if (topLevel.exitCode !== 0) return null;

		// Resolve the base commit — use provided ref (branch/tag/commit) or HEAD
		const baseCommitRef = baseRef || "HEAD";
		const headResult = await git(["rev-parse", baseCommitRef], parentCwd);
		if (headResult.exitCode !== 0) return null;
		const parentHeadCommit = headResult.stdout.trim();

		const suffix = sessionId.slice(-12);
		const branchName = `pi-subagent-${suffix}`;
		const worktreePath = path.join(os.tmpdir(), `pi-subagent-wt-${suffix}`);

		// Remove stale leftovers from a previous run with the same session id
		try { await git(["worktree", "remove", "--force", worktreePath], parentCwd); } catch { /* */ }
		try { await git(["branch", "-D", branchName], parentCwd); } catch { /* */ }

		const wtResult = await git(
			["worktree", "add", worktreePath, "-b", branchName, parentHeadCommit],
			parentCwd,
		);
		if (wtResult.exitCode !== 0) return null;

		return { worktreePath, branchName, parentHeadCommit };
	} catch {
		return null;
	}
}

/** Clean up a worktree after subagent completion. Auto-commits uncommitted
 *  changes, removes the worktree directory, and keeps the branch for review.
 *  If the branch has no commits beyond the parent HEAD it is deleted.
 *  Returns a status note for the delivered result. */
async function cleanupWorktree(rs: RunningSubagent): Promise<string> {
	const notes: string[] = [];
	const { worktreePath, isolationBranch, parentHeadCommit, parentCwd } = rs;
	if (!worktreePath || !isolationBranch || !parentHeadCommit) return "";

	try {
		// Stage and commit any uncommitted changes in the worktree
		await git(["add", "-A"], worktreePath);
		const diffResult = await git(["diff", "--cached", "--quiet"], worktreePath);
		if (diffResult.exitCode !== 0) {
			const commitMsg = `subagent(${rs.agentName}): ${rs.task.slice(0, 72)}`;
			await git(["commit", "-m", commitMsg], worktreePath);
			notes.push(`Uncommitted changes auto-committed to \`${isolationBranch}\`.`);
		}

		// Check whether the branch has diverged from the parent HEAD
		const finalHead = await git(["rev-parse", "HEAD"], worktreePath);
		const finalCommit = finalHead.stdout.trim();

		// Remove the worktree directory (branch ref stays in the repo)
		await git(["worktree", "remove", "--force", worktreePath], parentCwd);

		if (finalCommit === parentHeadCommit) {
			// No changes — delete the useless branch
			await git(["branch", "-D", isolationBranch], parentCwd);
			notes.push("No changes made — worktree cleaned up.");
		} else {
			notes.push(`Changes preserved on branch \`${isolationBranch}\`.`);
			notes.push(`Merge with: \`git merge ${isolationBranch}\``);
		}
	} catch (e: any) {
		notes.push(`Worktree cleanup error: ${e.message || e}`);
		// Best-effort: force-remove the worktree directory
		try { fs.rmSync(worktreePath, { recursive: true, force: true }); } catch { /* */ }
	}

	return notes.length > 0 ? `\n\n[Isolation] ${notes.join(" ")}` : "";
}

async function writeTempFile(name: string, content: string): Promise<{ dir: string; filePath: string }> {
	const tmpDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), "pi-async-subagent-"));
	const safeName = name.replace(/[^\w.-]+/g, "_");
	const filePath = path.join(tmpDir, `prompt-${safeName}.md`);
	await fs.promises.writeFile(filePath, content, { encoding: "utf-8", mode: 0o600 });
	return { dir: tmpDir, filePath };
}

function getFinalOutput(messages: any[]): string {
	for (let i = messages.length - 1; i >= 0; i--) {
		const msg = messages[i];
		if (msg.role === "assistant") {
			for (const part of msg.content) {
				if (part.type === "text") {
					return part.text.replace(/^\s*\[session_id:[^\]]*\]\s*$/gim, "").trimEnd();
				}
			}
		}
	}
	return "";
}

function extractFilesFromArgs(toolName: string, args: Record<string, any>): { read?: string; write?: string } {
	const result: { read?: string; write?: string } = {};
	const filePath = args.file_path || args.path;
	if (!filePath) return result;

	switch (toolName) {
		case "read":
			result.read = filePath;
			break;
		case "write":
		case "edit":
			result.write = filePath;
			break;
	}
	return result;
}

function formatProgress(rs: RunningSubagent): string {
	const p = rs.progress;
	const elapsed = Math.round((Date.now() - rs.startedAt) / 1000);
	const mins = Math.floor(elapsed / 60);
	const secs = elapsed % 60;
	return [
		`Agent: ${rs.agentName}`,
		`Session: ${rs.sessionId}`,
		`Turns: ${p.turns}`,
		`Elapsed: ${mins}m ${secs}s`,
		`Activity: ${p.currentActivity}`,
		p.filesRead.size > 0 ? `Files read: ${p.filesRead.size}` : null,
		p.filesModified.size > 0 ? `Files modified: ${p.filesModified.size}` : null,
		p.errors.length > 0 ? `Errors: ${p.errors.length}` : null,
	]
		.filter(Boolean)
		.join(" | ");
}

// ── RPC communication ──────────────────────────────────────────────────────

function rpcSend(stdin: NodeJS.WritableStream | null, command: Record<string, any>): void {
	if (!stdin || stdin.destroyed) return;
	stdin.write(JSON.stringify(command) + "\n");
}

interface RpcEvent {
	type: string;
	id?: string;
	message?: any;
	message_end?: any;
}

/**
 * Build the argv array for spawning a subagent pi process.
 * Extracted so tests can assert flag composition without spawning.
 * Does NOT include --append-system-prompt (the temp file path is
 * generated dynamically by the caller — writeTempFile).
 */
export function buildSubagentArgs(config: {
	model: string;
	tools: string[];
	excludeTools: string[];
	sessionFile?: string;
}): string[] {
	const args: string[] = ["--mode", "rpc"];
	if (config.model) args.push("--model", config.model);
	if (config.tools && config.tools.length > 0) args.push("--tools", config.tools.join(","));
	if (config.excludeTools && config.excludeTools.length > 0) {
		args.push("--exclude-tools", config.excludeTools.join(","));
	}
	if (config.sessionFile) {
		args.push("--session", config.sessionFile);
	}
	return args;
}

// ── Spawn & manage ──────────────────────────────────────────────────────────

async function spawnSubagent(
	pi: ExtensionAPI,
	ctx: any,
	agent: AgentConfig,
	task: string,
	cwd: string,
	sessionId: string,
	parentModel: string | undefined,
	inheritParentModel: boolean,
	worktreePath: string | null,
	isolationBranch: string | null,
	parentHeadCommit: string | null,
	parentCwdForCleanup: string,
	// When set, the subprocess loads an existing session file instead of
	// creating a new one. Used by subagent_resume.
	resumeSessionFile?: string,
): Promise<RunningSubagent> {
	const effectiveModel = inheritParentModel ? parentModel : (agent.model ?? "deepseek/deepseek-v4-flash");

	// Build spawn args via shared helper (also used by tests).
	const args = buildSubagentArgs({
		model: effectiveModel ?? "",
		tools: agent.tools ?? [],
		excludeTools: agent.excludeTools ?? [],
		sessionFile: resumeSessionFile,
	});

	let tmpDir: string | null = null;
	let tmpPath: string | null = null;
	if (agent.systemPrompt.trim()) {
		const tmp = await writeTempFile(agent.name, agent.systemPrompt);
		tmpDir = tmp.dir;
		tmpPath = tmp.filePath;
		args.push("--append-system-prompt", tmpPath);
	}

	const logPath = `/tmp/pi-subagent-${sessionId}.log`;
	const sockPath = `/tmp/pi-subagent-${sessionId}.sock`;

	const rs: RunningSubagent = {
		proc: null as any,
		sessionId,
		agentName: agent.name,
		task,
		cwd,
		startedAt: Date.now(),
		progress: newProgress(),
		messages: [],
		stdin: null,
		resolveOnStop: null,
		isDone: false,
		logPath,
		logLines: [],
		watchHandle: null,
		sockPath,
		sockServer: null as any,
		sockClients: new Set(),
		worktreePath,
		isolationBranch,
		parentHeadCommit,
		parentCwd: parentCwdForCleanup,
		parentTrackerKey: getParentTrackerKey(ctx),
		reviewParentRequirements: agent.reviewParentRequirements,
	};

	// Unix socket server for external viewers
	try { fs.unlinkSync(sockPath); } catch { /* not there yet */ }
	const sockServer = net.createServer((socket) => {
		rs.sockClients.add(socket);
		// Replay buffered lines so new viewer sees previous output
		for (const line of rs.logLines) {
			try { socket.write(line + "\n"); } catch { /* */ }
		}
		socket.on("close", () => { rs.sockClients.delete(socket); });
		socket.on("error", () => { rs.sockClients.delete(socket); });
	});
	sockServer.listen(sockPath, () => { /* ready */ });
	sockServer.on("error", () => { /* ignore */ });
	rs.sockServer = sockServer;

	// Open the live log file and write the header.
	const logEntry = (text: string) => {
		try { fs.appendFileSync(logPath, text + "\n"); } catch { /* */ }
		rs.logLines.push(text);
		rs.watchHandle?.requestRender();
		for (const client of rs.sockClients) {
			try { client.write(text + "\n"); } catch { rs.sockClients.delete(client); }
		}
	};

	// ANSI style helpers (Catppuccin-like)
	const S = {
		reset: "\x1b[0m",
		bold: "\x1b[1m",
		dim: "\x1b[2m",
		fgCyan: "\x1b[36m",
		fgGreen: "\x1b[32m",
		fgRed: "\x1b[31m",
		fgMagenta: "\x1b[35m",
		fgYellow: "\x1b[33m",
		fgBlue: "\x1b[34m",
		bgBlue: "\x1b[44m",
		bgRed: "\x1b[41m",
		toolPending: "\x1b[34m\x1b[1m",   // bold blue
		toolSuccess: "\x1b[32m",          // green
		toolError: "\x1b[31m\x1b[1m",     // bold red
		turnHdr: "\x1b[2m\x1b[36m",       // dim cyan
		think: "\x1b[2m",                  // dim
		headerFg: "\x1b[34m\x1b[1m",      // bold blue
		doneOk: "\x1b[32m\x1b[1m",        // bold green
		doneFail: "\x1b[31m\x1b[1m",      // bold red
		aside: "\x1b[2m\x1b[35m",          // dim magenta
	};
	const hdr = (lbl: string) => S.headerFg + lbl + S.reset + S.dim;

	logEntry(`${hdr("Agent:")} ${agent.name}  ${hdr("Session:")} ${sessionId}  ${hdr("CWD:")} ${cwd}${S.reset}`);
	logEntry(`${S.dim}Task: ${task.slice(0, 300)}${task.length > 300 ? "…" : ""}${S.reset}`);
	logEntry("");

	let currentTurn = 0;
	let pendingToolCalls: Map<string, string> = new Map(); // toolCallId → summary

	const invocation = getPiInvocation(args);
	const proc = spawn(invocation.command, invocation.args, {
		cwd,
		shell: false,
		stdio: ["pipe", "pipe", "pipe"],
		env: {
			...process.env,
			...(agent.allowedSubagents && agent.allowedSubagents.length > 0
				? { PI_SUBAGENT_ALLOWLIST: agent.allowedSubagents.join(",") }
				: {}),
		},
	});

	rs.proc = proc;
	rs.stdin = proc.stdin;

	let stdoutBuffer = "";

	// Debug logging, enabled via PI_ASYNC_DEBUG=1
	const debugLog = process.env.PI_ASYNC_DEBUG
		? (msg: string) => {
			try { fs.appendFileSync("/tmp/pi-async-debug.log", `[${rs.sessionId}] ${msg}\n`); } catch { /* */ }
		  }
		: () => {};
	debugLog("spawned cwd=" + cwd);

	const processLine = (line: string) => {
		if (!line.trim()) return;
		let event: RpcEvent;
		try {
			event = JSON.parse(line);
		} catch {
			return;
		}

		debugLog("ev:" + event.type);

		// ── Capture session info from get_state response ───────────────
		if (event.type === "response" && event.id === getStateId) {
			const data = (event as any).data;
			if ((event as any).success && data) {
				rs.sessionFile = data.sessionFile;
				rs.piSessionId = data.sessionId;
				debugLog(`get_state: sessionFile=${rs.sessionFile} piSessionId=${rs.piSessionId}`);
				// Persist to meta so subagent_resume can discover the file later.
				// The meta file was already written by the spawn caller with
				// the agent config fields; we add only sessionFile / piSessionId.
				updateMetaJson(sessionId, {
					sessionFile: rs.sessionFile,
					piSessionId: rs.piSessionId,
				});
			}
		}

		// ── Live log: turn boundaries ──────────────────────────────────
		if (event.type === "turn_start") {
			currentTurn++;
			logEntry(`${S.turnHdr}── Turn ${currentTurn} ──${S.reset}`);
		}

		// ── Live log: tool start ───────────────────────────────────────
		if (event.type === "tool_execution_start") {
			const tn: string = event.toolName || "";
			const ta: Record<string, any> = event.args || {};
			const summary = formatToolAction(tn, ta);
			pendingToolCalls.set(event.toolCallId, summary);
			logEntry(`  ${S.toolPending}▸ ${summary}${S.reset}`);
		}

		// ── Live log: tool end ─────────────────────────────────────────
		if (event.type === "tool_execution_end") {
			const summary = pendingToolCalls.get(event.toolCallId) || event.toolName || "tool";
			pendingToolCalls.delete(event.toolCallId);
			if (event.isError) {
				const errText = typeof event.result === "string"
					? event.result.slice(0, 120)
					: JSON.stringify(event.result).slice(0, 120);
				logEntry(`  ${S.toolError}✖ ${summary}${S.reset} ${S.fgRed}→ ERROR: ${errText}${S.reset}`);
			} else {
				// Extract readable result text
				let resultText = "";
				try {
					if (event.result?.content) {
						for (const c of event.result.content) {
							if (c.type === "text") resultText += c.text;
						}
					}
				} catch { /* */ }
				const trimmed = resultText.trim().slice(0, 200);
				if (trimmed) {
					logEntry(`  ${S.toolSuccess}─ ${trimmed.replace(/\n/g, "\n    ")}${S.reset}`);
				}
			}
		}

		// ── Live log: assistant message content ────────────────────────
		if (event.type === "message_end" && event.message) {
			const msg = event.message;
			if (msg.role === "assistant") {
				for (const part of msg.content) {
					// Thinking / reasoning tokens
					if (part.type === "thinking" && part.thinking?.trim()) {
						const tt = part.thinking.trim().slice(0, 500);
						logEntry(`  ${S.think}[thinking] ${tt.replace(/\n/g, `\n  ${S.think}[thinking] `)}${S.reset}`);
					}
					// Regular text
					if (part.type === "text" && part.text.trim()) {
						const t = part.text.trim();
						logEntry(`  ${t.replace(/\n/g, "\n  ")}${t.includes("\n") ? "" : ""}`);
					}
				}
			}
		}

		// Track session id from response
		if (event.type === "response" && event.id === "session") {
			// session header response
		}

		// Track messages
		if (event.type === "message_end" && event.message) {
			const msg = event.message;
			rs.messages.push(msg);

			if (msg.role === "assistant") {
				rs.progress.turns++;
				updateFooter(ctx);

				// Hard turn limit
				if (rs.progress.turns >= MAX_TURNS_HARD) {
					rs.progress.currentActivity = `hit turn limit (${MAX_TURNS_HARD}), stopping`;
					rs.progress.errors.push(`Turn limit reached (${MAX_TURNS_HARD})`);
					debugLog("turn-limit hit, killing proc");
					proc.kill("SIGTERM");
					setTimeout(() => { if (!proc.killed) proc.kill("SIGKILL"); }, HARD_KILL_DELAY_MS);
					return;
				}

				// Detect completion: text-only message (no tool calls) means the
				// model is done. RPC mode keeps stdin open so we must close it to
				// trigger process exit and fire the close handler.
				const hasToolCalls = msg.content.some((c: any) => c.type === "toolCall");
				const hasText = msg.content.some((c: any) => c.type === "text");
				debugLog("msg_end: tc=" + hasToolCalls + " txt=" + hasText + " resolve=" + !!rs.resolveOnStop);
				if (!hasToolCalls && hasText) {
					// Reviewer invocation guard: if this child has
				// `reviewParentRequirements` non-empty (i.e. it is itself an
				// implementer with a gate), check whether every required
				// reviewer kind has been spawned from it. The child's harness
				// writes a persisted tracker file at
				// `/tmp/pi-subagent-<childSessionId>.reviewers.json` for every
				// reviewer it spawns; we read that file here to make a
				// cross-process decision (the implementer runs in its own pi
				// process; its in-memory tracker is invisible to us — but the
				// file is the same one `subagent_review_status` reads, so the
				// soft-prompt check and the orchestrator's mechanical gate
				// share one source of truth).
				//
				// If any required reviewer kind is missing, inject a steer
				// prompt into the child's RPC stdin and SKIP the stdin.close()
				// so the implementer re-enters its agent loop with a corrective
				// message. We do NOT hard-stop the implementer: a hard stop
				// would lose model state for the corrective path. The soft
				// prompt is a polite nudge; the orchestrator's mechanical
				// `subagent_review_status` check is the actual gate.
				const required = rs.reviewParentRequirements;
				if (required && required.length > 0) {
					// The child's harness writes its reviewer-spawn tracker file
					// keyed by its own pi session ID (obtained via
					// getParentTrackerKey inside the child process). We read
					// by `rs.piSessionId` (captured from the child's get_state
					// response) so the file key matches. If get_state never
					// responded (child crashed before responding), skip the
					// soft-prompt guard — the orchestrator's mechanical
					// `subagent_review_status` check is the real gate.
					if (!rs.piSessionId) {
						debugLog(`review-gate: piSessionId not captured, skipping soft-prompt guard`);
						// Fall through to isDone/completion logic below
					} else {
					const trackerKey = rs.piSessionId;
					const trackerState = readPersistedSpawns(trackerKey);
					const spawnedKinds = new Set(trackerState.spawns.map((s) => s.reviewerKind));
					const missing = required.filter((k) => !spawnedKinds.has(k));
					if (missing.length > 0 && !trackerState.reviewCapReached) {
						const message =
							`[review-gate] You returned a final message without spawning all required reviewers. ` +
							`Missing: ${missing.join(", ")}. Per your post-implementation review section, you must launch ` +
							`both reviewers with \`isolate: false\` before reporting \`complete\`. Continuing.`;
						try {
							rpcSend(rs.stdin, {
								type: "prompt",
								message,
								streamingBehavior: "steer",
							});
							logEntry(`\x1b[33m[review-gate] soft prompt injected; missing reviewers: ${missing.join(", ")}\x1b[0m`);
							debugLog(`review-gate: soft prompt for missing=${missing.join(",")} child=${rs.sessionId} trackerKey=${trackerKey}`);
						} catch (e) {
							debugLog(`review-gate: rpcSend failed: ${e instanceof Error ? e.message : String(e)}`);
						}
						// Do NOT close stdin — the corrective prompt re-enters
						// the agent loop. We also do not set isDone=true here
						// because the agent is not actually done; it has a
						// corrective prompt to act on.
						return;
					}
					} // end else (piSessionId captured)
				} // end if (required)

					rs.progress.currentActivity = "completed, closing session";
					rs.isDone = true;
					debugLog("DONE! closing stdin");
					if (rs.stdin && !rs.stdin.destroyed) {
						rs.stdin.end();
					}
				}
			}
		}

		// Track tool execution for progress
		if (event.type === "tool_execution_start") {
			const toolName: string = event.toolName || "";
			const toolArgs: Record<string, any> = event.args || {};
			const files = extractFilesFromArgs(toolName, toolArgs);
			if (files.read) rs.progress.filesRead.add(files.read);
			if (files.write) rs.progress.filesModified.add(files.write);

			const actionSummary = formatToolAction(toolName, toolArgs);
			rs.progress.lastActions.push(actionSummary);
			if (rs.progress.lastActions.length > 5) rs.progress.lastActions.shift();
			rs.progress.currentActivity = actionSummary;
		}

		// Track errors
		if (event.type === "tool_execution_end" && event.isError) {
			const errMsg = typeof event.result === "string" ? event.result : JSON.stringify(event.result);
			rs.progress.errors.push(`${event.toolName}: ${errMsg.slice(0, 200)}`);
		}
	};

	proc.stdout.on("data", (data: Buffer) => {
		const raw = data.toString();
		stdoutBuffer += raw;
		const lines = stdoutBuffer.split("\n");
		stdoutBuffer = lines.pop() || "";
		for (const l of lines) {
			if (l.trim()) processLine(l);
		}
	});

	proc.stderr.on("data", (data: Buffer) => {
		// Accumulate stderr for debugging; don't surface to parent unless needed.
	});

	proc.on("close", async (code) => {
		debugLog("close: code=" + code + " resolve=" + !!rs.resolveOnStop + " done=" + rs.isDone + " turns=" + rs.progress.turns);
		if (stdoutBuffer.trim()) processLine(stdoutBuffer);

		// Write completion footer to live log
		const how = rs.isDone ? "Completed" : (code === 0 ? "Exited" : "Stopped");
		logEntry("");
		const style = rs.isDone ? S.doneOk : S.doneFail;
		logEntry(`${style}── ${how} (${rs.progress.turns} turns, exit ${code ?? "?"}) ──${S.reset}`);

		// Widget stays visible for user to review; they clear it with /watch off

		// Close socket server and clean up
		try {
			for (const client of rs.sockClients) client.destroy();
			rs.sockServer.close();
			fs.unlinkSync(sockPath);
		} catch { /* */ }

		// Mark the session as no longer running BEFORE cleanupWorktree (which
		// runs multiple git commands and can take seconds). Otherwise
		// subagent_resume would incorrectly reject with "already running"
		// during the cleanup window for a session that has completed.
		running.delete(sessionId);
		updateFooter(ctx);

		// Worktree isolation: commit changes, remove worktree, keep branch
		const isolationNote = await cleanupWorktree(rs);

		// Clean up temp files
		if (tmpPath) try { fs.unlinkSync(tmpPath); } catch { /* ignore */ }
		if (tmpDir) try { fs.rmdirSync(tmpDir); } catch { /* ignore */ }

		// If stop was requested, resolve that waiter (don't double-deliver).
		if (rs.resolveOnStop) {
			rs.resolveOnStop(getFinalOutput(rs.messages) + isolationNote);
			rs.resolveOnStop = null;
		} else {
			cancelWait();
			deliverResult(pi, rs, code ?? 0, isolationNote);
		}
	});

	proc.on("error", () => {
		running.delete(sessionId);
		updateFooter(ctx);
	});

	// Send get_state BEFORE the initial prompt so we capture the child's
	// real sessionFile and pi sessionId before any prompt processing begins.
	// Both commands run on the same RPC pipe; order is preserved by serial
	// stdin writes. If get_state never responds (child crashes immediately),
	// sessionFile remains undefined on rs — subagent_resume will error
	// gracefully for that session.
	const getStateId = `get-state-${randomUUID()}`;
	rpcSend(proc.stdin, { id: getStateId, type: "get_state" });
	rpcSend(proc.stdin, { type: "prompt", message: task });

	return rs;
}

// ── Live Log Viewer TUI Component ────────────────────────────────────────

class LogViewer {
	constructor(
		private lines: string[],
		private agentName: string,
		private sessionId: string,
		private maxHeight: number = 15,
	) {}

	/* TUI state */
	private lastLineCount = 0;
	private cachedWidth?: number;
	private cachedLines?: string[];

	invalidate(): void {
		this.cachedWidth = undefined;
		this.cachedLines = undefined;
	}

	render(width: number): string[] {
		// Skip cache if lines have grown (live stream)
		if (this.cachedLines && this.cachedWidth === width && this.lastLineCount === this.lines.length) {
			return this.cachedLines;
		}
		this.lastLineCount = this.lines.length;

		const tail = this.lines.slice(-this.maxHeight);
		this.cachedLines = [
			truncateToWidth(`▸ Subagent: ${this.agentName}  |  ${this.sessionId}`, width),
			"",
			...tail.map((l) => truncateToWidth(` ${l}`, width - 1)),
		];
		this.cachedWidth = width;
		return this.cachedLines;
	}
}

function formatToolAction(toolName: string, args: Record<string, any>): string {
	const shortenPath = (p: string) => {
		const home = os.homedir();
		return p.startsWith(home) ? `~${p.slice(home.length)}` : p;
	};
	const filePath = (args.file_path || args.path || "") as string;
	const short = filePath ? shortenPath(filePath) : "";

	switch (toolName) {
		case "read": return `read ${short}`;
		case "write": return `write ${short}`;
		case "edit": return `edit ${short}`;
		case "bash": {
			const cmd = (args.command as string) || "...";
			return `bash ${cmd.length > 40 ? cmd.slice(0, 40) + "..." : cmd}`;
		}
		case "grep": return `grep ${args.pattern || "..."}`;
		case "find": return `find ${args.pattern || "..."}`;
		case "subagent": return `subagent ${args.agent || "..."}`;
		case "checkpoint": return "checkpoint";
		default: return toolName;
	}
}

/** Cancel the active wait timer. */
function cancelWait(): void {
	if (activeWait) {
		clearTimeout(activeWait.timer);
		activeWait = null;
	}
}

function deliverResult(pi: ExtensionAPI, rs: RunningSubagent, exitCode: number, isolationNote?: string): void {
	const output = getFinalOutput(rs.messages) || "(no output)";

	const wasAborted = exitCode !== 0 && rs.progress.turns < MAX_TURNS_HARD;
	const prefix = wasAborted ? "[Subagent aborted]" : "[Subagent implement finished]";

	const message = [
		`${prefix} — session: ${rs.sessionId}`,
		`Task: ${rs.task.slice(0, 200)}${rs.task.length > 200 ? "..." : ""}`,
		`Turns: ${rs.progress.turns} | Files read: ${rs.progress.filesRead.size} | Files modified: ${rs.progress.filesModified.size}`,
		rs.progress.errors.length > 0
			? `Errors: ${rs.progress.errors.slice(0, 3).join("; ")}`
			: null,
		isolationNote || null,
		"---",
		output,
	]
		.filter(Boolean)
		.join("\n");

	pi.sendUserMessage(message, { deliverAs: "steer" });
}

// ── Footer ─────────────────────────────────────────────────────────────────

function updateFooter(ctx: any): void {
	if (running.size === 0) {
		ctx.ui.setStatus("subagent-async", undefined);
		return;
	}
	const parts: string[] = [];
	for (const rs of running.values()) {
		parts.push(`${rs.agentName} (${rs.progress.turns}t)`);
	}
	ctx.ui.setStatus("subagent-async", `subagents: ${parts.join(", ")}`);
}

// ── Extension entry point ──────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
	// ── Session lifecycle ──────────────────────────────────────────────

	pi.on("session_start", async (_event, ctx) => {
		try {
			const agents = discoverAgents(ctx.cwd, "user").agents;
			const agentNames = agents.map((agent) => agent.name).sort();
			const text = `[Subagents] ${agentNames.length} available: ${agentNames.join(", ") || "none"}`;
			pi.events.emit(STARTUP_SUMMARY_EVENT, { key: "subagents", order: 20, text });
		} catch (error) {
			const detail = error instanceof Error ? error.message : String(error);
			const text = `[Subagents] Unable to list available subagents: ${detail}`;
			pi.events.emit(STARTUP_SUMMARY_EVENT, { key: "subagents", order: 20, text });
		}

		// Re-attach to orphaned subagents from a previous session
		try {
			const sockDir = "/tmp";
			const files = fs.readdirSync(sockDir).filter((f) => f.startsWith("pi-subagent-") && f.endsWith(".sock"));
			for (const f of files) {
				const sid = f.replace("pi-subagent-", "").replace(".sock", "");
				if (running.has(sid)) continue; // already tracked

				const sockPath = path.join(sockDir, f);
				const logPath = sockPath.replace(".sock", ".log");
				const metaPath = sockPath.replace(".sock", ".meta.json");

				// Read metadata written at spawn time
				let meta: any = null;
				try { meta = JSON.parse(fs.readFileSync(metaPath, "utf-8")); } catch { continue; }

				// Parse current turns from log
				let turns = 0;
				try {
					const log = fs.readFileSync(logPath, "utf-8");
					turns = (log.match(/── Turn (\d+) ──/g) || []).length;
				} catch {}

				const rs: RunningSubagent = {
					proc: null as any,
					sessionId: sid,
					agentName: meta.agentName || "?",
					task: meta.task || "?",
					cwd: meta.cwd || ctx.cwd,
					startedAt: meta.startedAt || Date.now(),
					progress: { turns, filesRead: new Set(), filesModified: new Set(), errors: [], currentActivity: "recovered" },
					messages: [],
					stdin: null,
					resolveOnStop: null,
					isDone: false,
					logPath,
					logLines: [],
					watchHandle: null,
					sockPath,
					sockServer: null as any,
					sockClients: new Set(),
					worktreePath: meta.worktreePath || null,
					isolationBranch: meta.isolationBranch || null,
					parentHeadCommit: meta.parentHeadCommit || null,
					parentCwd: meta.parentCwd || ctx.cwd,
					// Recovered (orphan-reattached) subagents don't carry the
					// parent's tracker key from the metadata file. Use a stable
					// pid fallback so re-attached sessions don't pollute the
					// live tracker's view. If we had a `parentSessionId` field
					// in the meta file, we'd use it here instead.
					parentTrackerKey: getParentTrackerKey(ctx),
					reviewParentRequirements: undefined,
				};

				// Monitor via socket — when it closes, subagent exited.
				// The socket may already be dead (previous pi died without
				// cleanup), in which case connect() fails with ECONNREFUSED.
				// Without an `error` handler that event becomes an
				// uncaughtException and crashes the new pi session.
				const sock = net.createConnection(sockPath);
				let connected = false;
				sock.on("connect", () => {
					connected = true;
				});
				sock.on("error", () => {
					rs.sockClients.delete(sock);
					if (connected) return; // socket lived, then died — close handler will run
					// Orphan: previous session left a sock file behind with no listener.
					// Clean up and skip live tracking.
					try {
						fs.unlinkSync(sockPath);
					} catch {
						/* already gone */
					}
					running.delete(sid);
					updateFooter(ctx);
				});
				sock.on("close", () => {
					rs.sockClients.delete(sock);
					if (!connected) return; // orphan already handled in error handler
					rs.isDone = true;
					// Read final output from log
					let finalOutput = "(no output)";
					try {
						const log = fs.readFileSync(logPath, "utf-8");
						const match = log.match(/── (Completed|Exited|Stopped) \((\d+) turns, exit (\d+)\)/);
						if (match) {
							rs.progress.turns = parseInt(match[2]);
							finalOutput = log.split("── ").pop()?.trim() || finalOutput;
						}
					} catch {}
					deliverResult(pi, rs, 0, `\n[Isolation] Recovered from previous session.`);
					running.delete(sid);
					updateFooter(ctx);
				});

				rs.sockClients.add(sock);
				running.set(sid, rs);
				updateFooter(ctx);
			}
		} catch { /* best-effort */ }
	});

	pi.on("session_shutdown", () => {
		// Don't kill subagents — they survive parent reloads/restarts.
		// Their work commits to branches and is recoverable via git merge.
		// Socket servers and log files persist at /tmp/pi-subagent-<sid>.*
	});

	// ── /subagents command ──────────────────────────────────────────────

	pi.registerCommand("subagents", {
		description: "List running async subagents",
		handler: async (_args, ctx) => {
			if (running.size === 0) {
				ctx.ui.notify("No subagents running.");
				return;
			}
			const lines = Array.from(running.values()).map((rs) => formatProgress(rs));
			ctx.ui.notify(lines.join("\n\n"));
		},
	});

	pi.registerCommand("watch", {
		description: "Show a live log panel for a running subagent. Usage: /watch <session-id> or /watch off",
		handler: async (args, ctx) => {
			const sid = args.trim();

			// Turn off current watch if "off" or empty
			if (!sid || sid === "off") {
				ctx.ui.setWidget("subagent-watch", undefined);
				ctx.ui.notify("Watch cleared.");
				return;
			}

			// Match by full session ID or partial match
			let rs: RunningSubagent | undefined;
			for (const [id, r] of running) {
				if (id === sid || id.endsWith(sid)) {
					rs = r;
					break;
				}
			}
			if (!rs) {
				ctx.ui.notify(`No running subagent matching "${sid}".`);
				return;
			}

			// Build the widget
			const viewer = new LogViewer(
				rs.logLines,
				rs.agentName,
				rs.sessionId,
			);
			rs.watchHandle = ctx.ui.setWidget("subagent-watch", () => viewer, { placement: "belowEditor" });

			ctx.ui.notify(`Watching ${rs.agentName} (${rs.sessionId}). Use /watch off to close.`);
		},
	});

	// ── Tools ───────────────────────────────────────────────────────────

	const SubagentParams = Type.Object({
		agent: Type.String({ description: "Name of the agent to invoke" }),
		task: Type.String({ description: "Task to delegate" }),
		cwd: Type.Optional(Type.String({ description: "Working directory for the subagent process" })),
		inheritParentModel: Type.Optional(
			Type.Boolean({
				description: "Use the parent session's active model instead of the agent default.",
				default: false,
			}),
		),
		isolate: Type.Optional(
			Type.Boolean({
				description: "Run in an isolated git worktree to avoid file conflicts with concurrent subagents. Default: true. When true, a git worktree is created on a branch off the parent HEAD. On completion, uncommitted changes are auto-committed to that branch, the worktree is removed, and the branch remains for the calling session to inspect and merge.",
				default: true,
			}),
		),
		baseRef: Type.Optional(
			Type.String({
				description: "Git ref (commit hash, branch, or tag) to fork the worktree from. Defaults to HEAD if omitted. Use this when changes are on a feature branch that isn't ready for main — pass the branch name or ref. If changes are only in the working tree, create a feature branch, commit them, and pass that branch.",
			}),
		),
	});

	const StatusParams = Type.Object({
		session_id: Type.String({ description: "Session ID of the running subagent" }),
	});

	const SteerParams = Type.Object({
		session_id: Type.String({ description: "Session ID of the running subagent" }),
		message: Type.String({ description: "Steering message to inject" }),
	});

	const StopParams = Type.Object({
		session_id: Type.String({ description: "Session ID of the running subagent" }),
		final_message: Type.Optional(
			Type.String({ description: "Final steering message before stopping" }),
		),
	});

	// ── subagent ───────────────────────────────────────────────────────

	pi.registerTool({
		name: "subagent",
		label: "Subagent (async)",
		description:
			"Spawn a subagent that runs in the background. The parent remains interactive. " +
			"Use subagent_status to check progress, subagent_steer to inject guidance, " +
			"and subagent_stop to tell it to wrap up. Results are delivered as a user message when the subagent finishes. " +
			"After a subagent finishes, use `subagent_resume` with the same session_id to continue the same conversation instead of starting fresh.",
		parameters: SubagentParams,
		async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
			const sessionId = `subagent-${randomUUID()}`;
			const cwd = params.cwd ?? ctx.cwd;

			const agents = discoverAgents(cwd, "user").agents;
			const agent = agents.find((a) => a.name === params.agent);
			if (!agent) {
				const available = agents.map((a) => a.name).join(", ") || "none";
				return {
					content: [{ type: "text", text: `Unknown agent: "${params.agent}". Available: ${available}` }],
				};
			}

			// Check if the parent restricted sub-spawning via PI_SUBAGENT_ALLOWLIST
			const allowlist = process.env.PI_SUBAGENT_ALLOWLIST;
			if (allowlist) {
				const allowed = new Set(
					allowlist.split(",").map((a: string) => a.trim()).filter(Boolean),
				);
				if (!allowed.has(agent.name)) {
					const requested = agent.name;
					const allowedList = [...allowed].sort().join(", ") || "(empty)";
					return {
						content: [{
							type: "text",
							text:
								`Agent "${requested}" is not in this subagent's allowlist ` +
								`(${allowedList}). The parent's \`allowedSubagents\` field ` +
								`restricted sub-spawning to that set.`,
						}],
					};
				}
			}

			// Check if session is already running
			if (running.has(sessionId)) {
				return {
					content: [{ type: "text", text: `Subagent ${sessionId} is already running.` }],
				};
			}

			const parentModel = (() => {
				try { const m = ctx.getModel?.(); if (m?.provider && m?.id) return `${m.provider}/${m.id}`; } catch { /* */ }
				return undefined;
			})();

			// Worktree isolation (default: true)
			let effectiveCwd = cwd;
			let worktreePath: string | null = null;
			let isolationBranch: string | null = null;
			let parentHeadCommit: string | null = null;
			let isolationStatus = "";
			let taskForAgent = params.task;

			// Reviewers default to sharing the caller's worktree — they need
			// to see the implementer's uncommitted changes. But if the caller
			// explicitly passes baseRef (a specific branch/commit), the reviewer
			// gets its own worktree branched from that ref.
			if (agent.reviewerKind && params.isolate === undefined && !params.baseRef) {
				params.isolate = false;
			}

			if (params.isolate !== false) {
				const wt = await createWorktree(cwd, sessionId, params.baseRef);
				if (wt) {
					effectiveCwd = wt.worktreePath;
					worktreePath = wt.worktreePath;
					isolationBranch = wt.branchName;
					parentHeadCommit = wt.parentHeadCommit;
					isolationStatus = `\nIsolated in worktree \`${wt.branchName}\` (off \`${wt.parentHeadCommit.slice(0, 8)}\`)`;
					taskForAgent =
						`## Worktree isolation\n` +
						`You are running inside an isolated git worktree at \`${wt.worktreePath}\`, branched from \`${wt.parentHeadCommit.slice(0, 12)}\`. ` +
						`Your cwd is the worktree root. Edits go to the worktree branch; the harness auto-commits uncommitted changes, removes the worktree, and keeps the branch for review.\n\n` +
						`If the task lists paths like \`/Users/<owner>/<parent-repo>/foo/bar.rs\`, strip the parent prefix and use \`foo/bar.rs\` as a repo-relative path. Never \`cd\` to an absolute parent-repo path — that bypasses isolation.\n\n` +
						params.task;
				} else {
					isolationStatus = "\n(Worktree isolation unavailable — not a git repo or creation failed.)";
				}
			}

			const rs = await spawnSubagent(
				pi,
				ctx,
				agent,
				taskForAgent,
				effectiveCwd,
				sessionId,
				parentModel,
				params.inheritParentModel ?? false,
				worktreePath,
				isolationBranch,
				parentHeadCommit,
				cwd,
			);

			running.set(sessionId, rs);

		// Write metadata for recovery on session reload. Includes the full
		// agent config so subagent_resume can reproduce the original
		// configuration faithfully (storing the resolved model and system
		// prompt avoids drift if the user edits the agent definition between
		// spawn and resume). Uses atomic write (tmp + rename) to avoid torn
		// reads.
		const effectiveModel = params.inheritParentModel
			? parentModel
			: (agent.model ?? "deepseek/deepseek-v4-flash");
		writeMetaJson(sessionId, {
			agentName: agent.name,
			task: params.task,
			cwd,
			startedAt: rs.startedAt,
			worktreePath,
			isolationBranch,
			parentHeadCommit,
			parentCwd: cwd,
			tools: agent.tools ?? [],
			model: effectiveModel,
			systemPrompt: agent.systemPrompt,
			allowedSubagents: agent.allowedSubagents ?? [],
			excludeTools: agent.excludeTools ?? [],
		});

			// Reviewer-spawn tracker: if the spawned agent is a declared reviewer
			// (reviewerKind set in frontmatter), record this spawn under the
			// parent's key. The orchestrator reads this via `subagent_review_status`
			// to mechanically verify the gate. Recording happens AFTER the spawn
			// succeeds and BEFORE the result returns to the caller, so a child
			// session that hasn't yet been recorded is "not yet spawned" per the
			// work-order ordering invariant.
			if (agent.reviewerKind) {
				try {
					const parentKey = getParentTrackerKey(ctx);
					recordReviewerSpawn(parentKey, {
						reviewerKind: agent.reviewerKind,
						childSessionId: sessionId,
						childAgentName: agent.name,
						spawnedAt: Date.now(),
					});
					debugLog(`tracker: recorded ${agent.reviewerKind} spawn for parent=${parentKey} child=${sessionId}`);
				} catch (e) {
					debugLog(`tracker: record failed: ${e instanceof Error ? e.message : String(e)}`);
				}
			}

			updateFooter(ctx);

			return {
				content: [
					{
						type: "text",
						text: [
							`Subagent started: ${agent.name} (session: ${sessionId})${isolationStatus}`,
							`Task: ${params.task.slice(0, 200)}${params.task.length > 200 ? "..." : ""}`,
							"",
							"Watch live:",
							"```bash",
							`tail -f /tmp/pi-subagent-${sessionId}.log`,
							"```",
							"Or in-pi: /watch " + sessionId.slice(-8),
							"Or from another terminal: nc -U /tmp/pi-subagent-" + sessionId + ".sock",
							"Use /subagents to check progress.",
						].join("\n"),
					},
				],
			};
		},
	});

	// ── subagent_status ────────────────────────────────────────────────

	pi.registerTool({
		name: "subagent_status",
		label: "Subagent Status",
		description: "Check the progress of a running async subagent.",
		parameters: StatusParams,
		async execute(_toolCallId, params) {
			const rs = running.get(params.session_id);
			if (!rs) {
				// Check if it finished recently — result might still be in flight
				return {
					content: [
						{
							type: "text",
							text: `No running subagent found with session "${params.session_id}". It may have already finished or been stopped.`,
						},
					],
				};
			}

			return {
				content: [{ type: "text", text: formatProgress(rs) }],
			};
		},
	});

	// ── subagent_review_status ──────────────────────────────────────────
	// Read-only tool that returns the persisted reviewer-spawn tracker for a
	// given parent session id. The orchestrator calls this mechanically after
	// any implementer completion report lands; see `decisions/subagents/
	// 004-parallel-review-gate.md` (Reviewer invocation guard).
	//
	// Returns a JSON object safe to surface in the parent prompt:
	//   {
	//     "parentSessionId": "...",
	//     "updatedAt": 1234,
	//     "kindsPresent": ["implementation", "tests"],
	//     "kindsMissing": [],
	//     "spawns": [ { "reviewerKind": "implementation", "childSessionId": "subagent-...", "childAgentName": "review-code", "spawnedAt": 1234 } ]
	//   }
	// `parentSessionId` is required; the tool reads from
	// `/tmp/pi-subagent-<safe-id>.reviewers.json` (written by the parent's
	// harness on each spawn). If the file is missing or unreadable, returns
	// an empty spawns list — never throws.
	const ReviewStatusParams = Type.Object({
		parent_session_id: Type.String({
			description: "Session id of the parent whose reviewer spawns you want to inspect (e.g. the implementer's session id).",
		}),
	});

	pi.registerTool({
		name: "subagent_review_status",
		label: "Subagent Review Status",
		description:
			"Read-only tool. Returns the list of post-implementation reviewer kinds " +
			"that a given parent session has spawned, with each child session id. " +
			"Use after an implementer's completion report to mechanically verify that " +
			"every reviewer kind the implementer declared in `requires_parent_reviewers` " +
			"has actually been launched. The orchestrator's parallel-review gate uses " +
			"this to refuse `complete` until the implementer's tracker shows all required " +
			"kinds. Output is a JSON object with `parentSessionId`, `updatedAt`, " +
			"`kindsPresent`, `kindsMissing` (relative to no requirement list — always empty), " +
			"`reviewRounds`, `reviewCapReached`, and `spawns` (one entry per spawn).",
		parameters: ReviewStatusParams,
		async execute(_toolCallId, params) {
			const parentSessionId = params.parent_session_id;
			const trackerState = readPersistedSpawns(parentSessionId);
			// updatedAt is informational; recompute from file mtime if available
			let updatedAt: number | null = null;
			try {
				const path = reviewStatusPath(parentSessionId);
				const stat = fs.statSync(path);
				updatedAt = stat.mtimeMs;
			} catch { /* missing file — updatedAt stays null */ }
			const kindsPresent = Array.from(new Set(trackerState.spawns.map((s) => s.reviewerKind))).sort();
			const payload = {
				parentSessionId,
				updatedAt,
				kindsPresent,
				kindsMissing: [], // populated by orchestrator if it knows the requirement set
				reviewRounds: trackerState.reviewRounds,
				reviewCapReached: trackerState.reviewCapReached,
				spawns: trackerState.spawns,
			};
			return {
				content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
			};
		},
	});

	// ── subagent_resume ───────────────────────────────────────────────
	// Resumes a previously-completed subagent session by spawning a new
	// RPC process that loads the existing session JSONL and continues
	// from where the previous run stopped. Preserves the original agent
	// config (tools, model, system prompt) from the spawn-time meta file.

	/**
	 * Validate a meta object read from disk for resume. Returns either
	 * { ok: true } or { ok: false, error, isError }. Extracted so tests
	 * can cover all error paths without spawning real processes.
	 */
	function validateResumeMeta(
		meta: Record<string, any> | null,
		sid: string,
	): { ok: true } | { ok: false; error: string; isError: boolean } {
		if (!meta) {
			return {
				ok: false,
				error: `No prior session found with id "${sid}". The session may have been purged or never existed. Spawn a fresh subagent instead.`,
				isError: false,
			};
		}
		if (!meta.sessionFile) {
			return {
				ok: false,
				error: `Session file not captured for "${sid}". The original subagent may have crashed before reporting its session. Spawn a fresh subagent instead.`,
				isError: true,
			};
		}
		if (!fs.existsSync(meta.sessionFile)) {
			return {
				ok: false,
				error: `Session file ${meta.sessionFile} no longer exists. Cannot resume.`,
				isError: true,
			};
		}
		return { ok: true };
	}

	/**
	 * Build an AgentConfig from persisted meta fields. Uses the stored
	 * resolved model and full system prompt so resume reproduces the
	 * original config exactly (no drift from user editing agent files).
	 */
	function buildAgentConfigFromMeta(meta: Record<string, any>): AgentConfig {
		return {
			name: meta.agentName || "?",
			description: "",
			systemPrompt: meta.systemPrompt || "",
			tools: Array.isArray(meta.tools) ? meta.tools : [],
			model: meta.model,
			source: "user",
			filePath: "",
			allowedSubagents: Array.isArray(meta.allowedSubagents) ? meta.allowedSubagents : undefined,
			excludeTools: Array.isArray(meta.excludeTools) ? meta.excludeTools : undefined,
		};
	}

	const ResumeParams = Type.Object({
		session_id: Type.String({
			minLength: 1,
			description:
				"Session ID of a previously completed subagent to resume " +
				"(full 'subagent-<UUID>' or last 8+ chars).",
		}),
		task: Type.String({
			description: "Follow-up task to send to the resumed session.",
		}),
		cwd: Type.Optional(
			Type.String({
				description:
					"Working directory; defaults to the original subagent's recorded parentCwd.",
			}),
		),
	});

	pi.registerTool({
		name: "subagent_resume",
		label: "Subagent Resume",
		description:
			"Resume a previously-completed subagent session with a follow-up prompt. " +
			"Spawns a new RPC process that loads the existing session file and continues " +
			"from where the previous run stopped, preserving conversation history and " +
			"model state. The resumed session runs in the original recorded parent cwd " +
			"and does NOT re-establish the original isolation worktree. " +
			"Use this to send a follow-up question or corrective prompt to a reviewer " +
			"that has already finished, without re-seeding the full context.",
		parameters: ResumeParams,
		async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
			// 1. Resolve the meta file by full or partial session id
			let sid: string;
			let resolvedMeta: Record<string, any>;
			try {
				const r = resolveSubagentMeta(params.session_id);
				if (!r) {
					const v = validateResumeMeta(null, params.session_id);
					return {
						content: [{ type: "text", text: v.ok ? "" : v.error }],
						isError: (v as any).isError,
					};
				}
				sid = r.sid;
				resolvedMeta = r.meta;

				// 2. Validate meta fields (sessionFile present, file on disk)
				const validation = validateResumeMeta(resolvedMeta, sid);
				if (!validation.ok) {
					return {
						content: [{ type: "text", text: validation.error }],
						isError: validation.isError,
					};
				}
			} catch (e: any) {
				return {
					content: [{ type: "text", text: e.message }],
					isError: true,
				};
			}

	
			// 3. Validate no running subagent with the same id
			if (running.has(sid)) {
				return {
					content: [{
						type: "text",
						text: `Subagent "${sid}" is already running.`,
					}],
					isError: true,
				};
			}

			// 4. Build a synthetic AgentConfig from the persisted meta fields.
			const syntheticAgent = buildAgentConfigFromMeta(resolvedMeta);
			const cwd = params.cwd ?? (resolvedMeta.parentCwd || ctx.cwd);

			// 5. Spawn the resumed RPC process under the SAME subagent-<UUID> key.
			// No worktree isolation — resumed sessions run in the recorded parentCwd.
			const rs = await spawnSubagent(
				pi,
				ctx,
				syntheticAgent,
				params.task,
				cwd,
				sid,
				undefined, // parentModel — not meaningful for resume
				false, // inheritParentModel — already resolved in meta
				null, // worktreePath
				null, // isolationBranch
				null, // parentHeadCommit
				cwd,
				resolvedMeta.sessionFile, // resumeSessionFile
			);

			running.set(sid, rs);
			updateFooter(ctx);

			// 6. DO NOT record a new reviewer-spawn tracker entry. The original
			// spawn already recorded it; resume continues the same logical session.

			return {
				content: [
					{
						type: "text",
						text: [
							`Subagent resumed: ${syntheticAgent.name} (session: ${sid})`,
							`Task: ${params.task.slice(0, 200)}${params.task.length > 200 ? "..." : ""}`,
							"",
							"Watch live:",
							"```bash",
							`tail -f /tmp/pi-subagent-${sid}.log`,
							"```",
							"Or in-pi: /watch " + sid.slice(-8),
							"Or from another terminal: nc -U /tmp/pi-subagent-" + sid + ".sock",
							"Use /subagents to check progress.",
						].join("\n"),
					},
				],
			};
		},
	});

	// ── wait ──────────────────────────────────────────────────────────

	const WaitParams = Type.Object({
		seconds: Type.Number({ description: "Number of seconds to wait", minimum: 1, maximum: 300 }),
	});

	pi.registerTool({
		name: "wait",
		label: "Wait",
		description: "Set a non-blocking timer. Returns immediately. After N seconds, if no subagent has completed during the interval, a wake-up message is sent. If a subagent completes before the timer fires, the wake-up is cancelled. Only one wait can be active at a time — calling wait again while waiting returns an error. Use this instead of 'sleep' when waiting for subagent results.",
		parameters: WaitParams,
		async execute(_toolCallId, params) {
			if (activeWait) {
				return { content: [{ type: "text", text: `Already waiting — a timer is active.` }], terminate: true };
			}

			const w = { timer: null as NodeJS.Timeout | null };
			w.timer = setTimeout(() => {
				activeWait = null;
				pi.sendUserMessage(`[timer] ${params.seconds}s elapsed — no subagent completed. Use subagent_status to check.`, { deliverAs: "steer" });
			}, params.seconds * 1000);
			activeWait = w;

			return { content: [{ type: "text", text: `Timer set for ${params.seconds}s.` }], terminate: true };
		},
	});

	// ── subagent_steer ─────────────────────────────────────────────────

	pi.registerTool({
		name: "subagent_steer",
		label: "Subagent Steer",
		description: "Inject a steering message into a running async subagent. The message is delivered before the subagent's next LLM call.",
		parameters: SteerParams,
		async execute(_toolCallId, params) {
			const rs = running.get(params.session_id);
			if (!rs) {
				return {
					content: [
						{
							type: "text",
							text: `No running subagent found with session "${params.session_id}".`,
						},
					],
				};
			}

			rpcSend(rs.stdin, {
				type: "prompt",
				message: params.message,
				streamingBehavior: "steer",
			});

			return {
				content: [
					{
						type: "text",
						text: `Steering message sent to ${rs.agentName} (${params.session_id}): "${params.message}"`,
					},
				],
			};
		},
	});

	// ── subagent_stop ──────────────────────────────────────────────────

	pi.registerTool({
		name: "subagent_stop",
		label: "Subagent Stop",
		description: "Tell a running async subagent to wrap up and return a summary. Waits up to 5 minutes for the subagent to finish.",
		parameters: StopParams,
		async execute(_toolCallId, params, signal) {
			const rs = running.get(params.session_id);
			if (!rs) {
				return {
					content: [
						{
							type: "text",
							text: `No running subagent found with session "${params.session_id}".`,
						},
					],
				};
			}

			// Send final steer if provided
			const finalMsg = params.final_message || "Wrap up your current work and return a summary. Do not start new tasks.";
			rpcSend(rs.stdin, {
				type: "prompt",
				message: finalMsg,
				streamingBehavior: "steer",
			});

		// Wait for subagent to finish, with timeout
			// The worker won't exit on its own (RPC mode keeps it alive).
			// We rely on the isDone detection (text-only message) to close
			// stdin, which triggers process exit → close handler → resolveOnStop.
			// Fallback: force-kill after a generous timeout.
			const result = await new Promise<string>((resolve) => {
				let resolved = false;
				const finish = (text: string) => {
					if (resolved) return;
					resolved = true;
					clearTimeout(fallbackTimeout);
					if (signal) {
						try { signal.removeEventListener("abort", onAbort); } catch { /* */ }
					}
					resolve(text);
				};

				// Fallback: force-kill the process if it doesn't finish naturally.
				const fallbackTimeout = setTimeout(() => {
					rs.proc.kill("SIGTERM");
					setTimeout(() => {
						if (!rs.proc.killed) rs.proc.kill("SIGKILL");
						finish("[Force-stopped after timeout]");
					}, HARD_KILL_DELAY_MS);
				}, STOP_TIMEOUT_MS);

				rs.resolveOnStop = (finalOutput?: string) => {
					finish(finalOutput || "(no output)");
				};

				// If already done (subagent finished before we set resolveOnStop),
				// close stdin now to trigger exit.
				if (rs.isDone && rs.stdin && !rs.stdin.destroyed) {
					rs.stdin.end();
				}

				const onAbort = () => finish("[Aborted]");
				if (signal) {
					if (signal.aborted) onAbort();
					else signal.addEventListener("abort", onAbort, { once: true });
				}
			});

			return {
				content: [
					{
						type: "text",
						text: `${rs.agentName} (${params.session_id}) stopped.\n\n${result}`,
					},
				],
			};
		},
	});
}
